'use strict';
const crypto = require('crypto');
const fs     = require('fs');
const path   = require('path');

const envPath = path.join(__dirname, '.env');

if (fs.existsSync(envPath)) {
  console.log('.env already exists. Delete it first to regenerate secrets.');
  process.exit(0);
}

const accessSecret  = crypto.randomBytes(64).toString('hex');
const refreshSecret = crypto.randomBytes(64).toString('hex');

const content = `# LoopWear — Environment Configuration
# Generated by: npm run setup

PORT=3000
NODE_ENV=development
CLIENT_ORIGIN=http://localhost:3000

JWT_ACCESS_SECRET=${accessSecret}
JWT_REFRESH_SECRET=${refreshSecret}
`;

fs.writeFileSync(envPath, content, 'utf8');
console.log('✓  .env created with cryptographically secure random secrets.');
console.log('   Next: npm install && npm start\n');
